name: Build and Deploy Docker Image

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t mremule/gravvits:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push mremule/gravvits:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH }}
          script: |
            docker pull mremule/gravvits:${{ github.sha }}
            docker stop gravvits || true
            docker rm gravvits || true
            docker run -d --name gravvits -p 8000:8000 mremule/gravvits:${{ github.sha }}

      - name: Set Commit Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const state = '${{ job.status }}'
            const targetUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            const description = state === 'success' ?  '🟢 SUCCESS: BUILD & DEPLOY 🐳' : '❌ Something went wrong while building and deploying...'

            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              context: 'build-and-deploy',
              target_url: targetUrl,
              description: description
            })