name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      docker: ${{ steps.filter.outputs.docker }}

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Find Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - '**/*.py'
              - 'poetry.lock'
              - 'pyproject.toml'
            docker:
              - '**/Dockerfile'
              - '**/docker-compose.yml'

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/lint-python.yml

  build-and-deploy:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || ( needs.changes.outputs.backend == 'false' && needs.changes.outputs.docker == 'true' )  }}
    uses: ./.github/workflows/build-and-deploy.yml