name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH: ${{ secrets.EC2_SSH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH }}
          script: |
            cd ~/gravvits
            git pull origin main
            docker compose up -d --build

      - name: Set Commit Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const state = '${{ job.status }}'
            const targetUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            const description = state === 'success' ?  '⚓️ SUCCESS: DEPLOY' : '❌ Something went wrong while deploying...'

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              context: 'deploy',
              target_url: targetUrl,
              description: description
            })