name: Lint Python

on:
  workflow_call:
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Run Black
        working-directory: app
        run: |
          poetry run black --check --diff .

      - name: Set Commit Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const state = '${{ job.status }}'
            const description = state === 'success' ?  '✏️ SUCCESS: LINT PYTHON' : '❌ Something went wrong while linting python...'
            
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: state,
              context: 'lint-python',
              target_url: context.payload.repository.commits_url,
              description: description
            })